---
title: "RESUME"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---
#### BAOYI FENG
100 Haven Ave NY ny10032 | +1 9175441721 | bf2506@cumc.columbia.edu
**---------------------------------------------------------------------------------------------------------------------------------------------------------------**

#### RESEARCH EXPERIENCE

**Epidemiological Study of Anemia in Dogs in Xihu District, Hangzhou City** <br>
March 2021 - June 2021 <br>
Research Assistant to Prof. Huanan Wang <br>

**Analysis of the FCoV nsp3c Difference between Abdominal Cavity and Gut**<br>
June 2019 - Nov. 2020 <br>
Research Assistant to Prof. Xiaojuan Zheng <br>

**Study on the Target of Platycodin D Adjuvant Based on Metabonomics**<br>
July 2020 - June 2021 <br>
Research Assistant to Prof. Hongxiang Sun <br>

**---------------------------------------------------------------------------------------------------------------------------------------------------------------**

#### INTERNSHIP EXPERIENCE

**Intern | Shanghai Jun’an Special Layer Farm** <br>                            Sept. 2020 – Nov. 2020 <br>

**Veterinarian Assistant | Jia Chong Animal Hospital**<br>                      May 2020 – July 2020 <br>

**Veterinarian Assistant | Zhejiang University Animal Hospital**<br>          July 2020 <br>

**---------------------------------------------------------------------------------------------------------------------------------------------------------------**

#### ANIMAL WELFARE ACTIVITIES

**Animal Rescue Team Member | Animal Protection Association of Zhejiang University**<br>
June 2018 - Present <br>

**International Volunteer | IEAEC Australia Volunteer Service** <br>            July 2018 - Aug. 2018 <br>
